-- SIMPEG schema for the static React/Supabase application.
-- Run on a new Supabase project before the security migration.
-- Schema definition for SIMPEG PostgreSQL database and Supabase client.
-- No default users or passwords are seeded. Create Auth users explicitly.

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE pegawai (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nip VARCHAR(50) UNIQUE,
    nama VARCHAR(150) NOT NULL,
    tempat_lahir VARCHAR(100),
    tanggal_lahir DATE,
    jenis_kelamin VARCHAR(20),
    agama VARCHAR(30),
    status_perkawinan VARCHAR(30),
    alamat TEXT,
    no_hp VARCHAR(30),
    email VARCHAR(100),
    tanggal_masuk DATE,
    tanggal_masuk_kerja DATE,
    status_kepegawaian VARCHAR(50) NOT NULL DEFAULT 'Dosen PNS',
    kategori VARCHAR(50),
    jabatan VARCHAR(100),
    jabatan_fungsional VARCHAR(100),
    kepangkatan VARCHAR(100),
    pangkat_golongan VARCHAR(100),
    tmt_pangkat DATE,
    tmt_jabatan DATE,
    unit_kerja VARCHAR(100),
    pendidikan_terakhir VARCHAR(50),
    universitas VARCHAR(150),
    jurusan VARCHAR(100),
    tahun_lulus INTEGER,
    ijazah TEXT,
    sk_inpassing_2025 SMALLINT NOT NULL DEFAULT 0 CHECK (sk_inpassing_2025 IN (0, 1)),
    file_ijazah TEXT,
    file_kepangkatan TEXT,
    file_jabatan_fungsional TEXT,
    foto TEXT,
    foto_url TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Legacy login credentials are retained only for migration/reference and must not
-- be queried from the browser. Authentication is exclusively Supabase Auth.
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255),
    nama_lengkap VARCHAR(150) NOT NULL,
    role VARCHAR(30) NOT NULL DEFAULT 'pegawai' CHECK (role IN ('developer', 'admin', 'bendahara', 'pegawai')),
    pegawai_id BIGINT UNIQUE REFERENCES pegawai(id) ON DELETE SET NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE pegawai_dokumen (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pegawai_id BIGINT NOT NULL REFERENCES pegawai(id) ON DELETE CASCADE,
    jenis_dokumen VARCHAR(100) NOT NULL,
    nama_file VARCHAR(255) NOT NULL,
    file_url TEXT NOT NULL,
    keterangan TEXT,
    uploaded_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE surat_masuk (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nomor_surat VARCHAR(100) NOT NULL,
    tanggal_surat DATE NOT NULL,
    tanggal_terima DATE,
    tanggal_diterima DATE,
    pengirim VARCHAR(150) NOT NULL,
    perihal TEXT NOT NULL,
    disposisi TEXT,
    keterangan TEXT,
    file_url TEXT,
    file_surat TEXT,
    created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE surat_keluar (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nomor_surat VARCHAR(100) NOT NULL,
    tanggal_surat DATE NOT NULL,
    tujuan VARCHAR(150) NOT NULL,
    perihal TEXT NOT NULL,
    keterangan TEXT,
    file_url TEXT,
    file_surat TEXT,
    created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE surat_keputusan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nomor_sk VARCHAR(100) NOT NULL,
    tanggal_sk DATE NOT NULL,
    pegawai_id BIGINT REFERENCES pegawai(id) ON DELETE SET NULL,
    perihal TEXT,
    tentang TEXT NOT NULL,
    keterangan TEXT,
    file_url TEXT,
    file_sk TEXT,
    created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE absensi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pegawai_id BIGINT NOT NULL REFERENCES pegawai(id) ON DELETE CASCADE,
    tanggal DATE NOT NULL,
    jam_masuk TIME,
    jam_keluar TIME,
    status VARCHAR(30) NOT NULL DEFAULT 'hadir',
    keterangan TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (pegawai_id, tanggal)
);

CREATE TABLE pengajuan_izin (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pegawai_id BIGINT NOT NULL REFERENCES pegawai(id) ON DELETE CASCADE,
    tanggal DATE NOT NULL,
    jenis VARCHAR(30) NOT NULL CHECK (jenis IN ('izin', 'sakit', 'dinas')),
    keterangan TEXT NOT NULL,
    file_bukti TEXT,
    status VARCHAR(30) NOT NULL DEFAULT 'menunggu',
    catatan_admin TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (pegawai_id, tanggal)
);

CREATE TABLE kas_transaksi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jenis_kas VARCHAR(20) NOT NULL CHECK (jenis_kas IN ('kas_kecil', 'kas_besar')),
    tipe VARCHAR(20) NOT NULL CHECK (tipe IN ('pemasukan', 'pengeluaran')),
    kategori VARCHAR(100) NOT NULL,
    jumlah NUMERIC(15, 2) NOT NULL DEFAULT 0,
    keterangan TEXT,
    tanggal DATE NOT NULL,
    created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE gaji (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pegawai_id BIGINT NOT NULL REFERENCES pegawai(id) ON DELETE CASCADE,
    bulan INTEGER NOT NULL CHECK (bulan BETWEEN 1 AND 12),
    tahun INTEGER NOT NULL,
    gaji_pokok NUMERIC(15, 2) NOT NULL DEFAULT 0,
    tunj_fungsional NUMERIC(15, 2) NOT NULL DEFAULT 0,
    tunj_struktural NUMERIC(15, 2) NOT NULL DEFAULT 0,
    tunj_kesejahteraan NUMERIC(15, 2) NOT NULL DEFAULT 0,
    status_kawin SMALLINT NOT NULL DEFAULT 0 CHECK (status_kawin IN (0, 1)),
    tunj_kawin NUMERIC(15, 2) NOT NULL DEFAULT 0,
    jumlah_anak INTEGER NOT NULL DEFAULT 0,
    tunj_anak NUMERIC(15, 2) NOT NULL DEFAULT 0,
    tunj_beras NUMERIC(15, 2) NOT NULL DEFAULT 200000,
    tunjangan_jabatan NUMERIC(15, 2) NOT NULL DEFAULT 0,
    tunjangan_keluarga NUMERIC(15, 2) NOT NULL DEFAULT 0,
    tunjangan_makan NUMERIC(15, 2) NOT NULL DEFAULT 0,
    tunjangan_transport NUMERIC(15, 2) NOT NULL DEFAULT 0,
    tunjangan_lain NUMERIC(15, 2) NOT NULL DEFAULT 0,
    total_tunjangan NUMERIC(15, 2) NOT NULL DEFAULT 0,
    potongan_bpjs NUMERIC(15, 2) NOT NULL DEFAULT 0,
    potongan_pajak NUMERIC(15, 2) NOT NULL DEFAULT 0,
    potongan_lain NUMERIC(15, 2) NOT NULL DEFAULT 0,
    pot_bpjs_tk NUMERIC(15, 2) NOT NULL DEFAULT 0,
    pot_bpjs_kes NUMERIC(15, 2) NOT NULL DEFAULT 0,
    pot_koperasi NUMERIC(15, 2) NOT NULL DEFAULT 20000,
    potongan NUMERIC(15, 2) NOT NULL DEFAULT 0,
    total_potongan NUMERIC(15, 2) NOT NULL DEFAULT 0,
    total_gaji NUMERIC(15, 2) NOT NULL DEFAULT 0,
    status_pembayaran VARCHAR(20) NOT NULL DEFAULT 'draft',
    tanggal_bayar DATE,
    catatan TEXT,
    keterangan TEXT,
    created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (pegawai_id, bulan, tahun)
);

CREATE TABLE pengaturan_ttd (
    key_name TEXT PRIMARY KEY,
    key_value TEXT NOT NULL
);

CREATE INDEX idx_pegawai_nama ON pegawai (nama);
CREATE INDEX idx_surat_masuk_tgl ON surat_masuk (tanggal_surat);
CREATE INDEX idx_surat_keluar_tgl ON surat_keluar (tanggal_surat);
CREATE INDEX idx_sk_tgl ON surat_keputusan (tanggal_sk);
CREATE INDEX idx_absensi_pegawai_tgl ON absensi (pegawai_id, tanggal);
CREATE INDEX idx_izin_created_at ON pengajuan_izin (created_at DESC);
CREATE INDEX idx_kas_tanggal ON kas_transaksi (tanggal DESC);
CREATE INDEX idx_gaji_periode ON gaji (tahun, bulan);
