-- Skema PostgreSQL awal untuk aplikasi SIMPEG.
-- Jalankan melalui Supabase Dashboard > SQL Editor pada project yang masih kosong.

CREATE TABLE pegawai (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama TEXT NOT NULL,
    tempat_lahir TEXT,
    tanggal_lahir DATE,
    nip VARCHAR(32),
    kepangkatan TEXT,
    tmt_pangkat DATE,
    jabatan_fungsional TEXT,
    tmt_jabatan DATE,
    sk_inpassing_2025 SMALLINT NOT NULL DEFAULT 0 CHECK (sk_inpassing_2025 IN (0, 1)),
    ijazah TEXT,
    status_kepegawaian TEXT NOT NULL DEFAULT 'Dosen PNS',
    tanggal_masuk_kerja DATE,
    file_ijazah TEXT,
    file_kepangkatan TEXT,
    file_jabatan_fungsional TEXT,
    foto TEXT
);

CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    nama_lengkap TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'admin' CHECK (role IN ('admin', 'developer', 'bendahara', 'pegawai')),
    pegawai_id INTEGER UNIQUE REFERENCES pegawai(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE absensi (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pegawai_id INTEGER NOT NULL REFERENCES pegawai(id),
    tanggal DATE NOT NULL,
    jam_masuk TIME,
    jam_keluar TIME,
    status TEXT NOT NULL DEFAULT 'hadir',
    keterangan TEXT,
    UNIQUE (pegawai_id, tanggal)
);

CREATE TABLE pengajuan_izin (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pegawai_id INTEGER NOT NULL REFERENCES pegawai(id),
    tanggal DATE NOT NULL,
    jenis TEXT NOT NULL CHECK (jenis IN ('izin', 'sakit', 'dinas')),
    keterangan TEXT NOT NULL,
    file_bukti TEXT,
    status TEXT NOT NULL DEFAULT 'menunggu',
    catatan_admin TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (pegawai_id, tanggal)
);

CREATE TABLE gaji (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pegawai_id INTEGER NOT NULL REFERENCES pegawai(id),
    bulan SMALLINT NOT NULL CHECK (bulan BETWEEN 1 AND 12),
    tahun INTEGER NOT NULL,
    gaji_pokok NUMERIC(14, 2) NOT NULL DEFAULT 0,
    tunj_fungsional NUMERIC(14, 2) NOT NULL DEFAULT 0,
    tunj_struktural NUMERIC(14, 2) NOT NULL DEFAULT 0,
    tunj_kesejahteraan NUMERIC(14, 2) NOT NULL DEFAULT 0,
    status_kawin SMALLINT NOT NULL DEFAULT 0 CHECK (status_kawin IN (0, 1)),
    tunj_kawin NUMERIC(14, 2) NOT NULL DEFAULT 0,
    jumlah_anak INTEGER NOT NULL DEFAULT 0,
    tunj_anak NUMERIC(14, 2) NOT NULL DEFAULT 0,
    tunj_beras NUMERIC(14, 2) NOT NULL DEFAULT 200000,
    tunjangan_makan NUMERIC(14, 2) NOT NULL DEFAULT 0,
    tunjangan_lain NUMERIC(14, 2) NOT NULL DEFAULT 0,
    pot_bpjs_tk NUMERIC(14, 2) NOT NULL DEFAULT 0,
    pot_bpjs_kes NUMERIC(14, 2) NOT NULL DEFAULT 0,
    pot_koperasi NUMERIC(14, 2) NOT NULL DEFAULT 20000,
    potongan NUMERIC(14, 2) NOT NULL DEFAULT 0,
    total_gaji NUMERIC(14, 2) NOT NULL DEFAULT 0,
    catatan TEXT,
    UNIQUE (pegawai_id, bulan, tahun)
);

CREATE TABLE kas_transaksi (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tanggal DATE NOT NULL,
    jenis_kas TEXT NOT NULL CHECK (jenis_kas IN ('kas_kecil', 'kas_besar')),
    tipe TEXT NOT NULL CHECK (tipe IN ('pemasukan', 'pengeluaran')),
    kategori TEXT NOT NULL,
    keterangan TEXT,
    jumlah NUMERIC(14, 2) NOT NULL,
    created_by INTEGER REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE pengaturan_ttd (
    key_name TEXT PRIMARY KEY,
    key_value TEXT NOT NULL
);

CREATE TABLE surat_keputusan (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nomor_sk TEXT NOT NULL,
    tanggal_sk DATE NOT NULL,
    tentang TEXT NOT NULL,
    file_sk TEXT
);

CREATE TABLE surat_masuk (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nomor_surat TEXT NOT NULL,
    tanggal_surat DATE NOT NULL,
    tanggal_diterima DATE NOT NULL,
    pengirim TEXT NOT NULL,
    perihal TEXT NOT NULL,
    file_surat TEXT
);

CREATE TABLE surat_keluar (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nomor_surat TEXT NOT NULL,
    tanggal_surat DATE NOT NULL,
    tujuan TEXT NOT NULL,
    perihal TEXT NOT NULL,
    file_surat TEXT
);

CREATE INDEX absensi_tanggal_idx ON absensi (tanggal);
CREATE INDEX izin_created_at_idx ON pengajuan_izin (created_at DESC);
CREATE INDEX kas_tanggal_idx ON kas_transaksi (tanggal DESC);
CREATE INDEX gaji_periode_idx ON gaji (tahun, bulan);