const text = (name, label, extra = {}) => ({ name, label, type: "text", ...extra });
const date = (name, label, extra = {}) => ({ name, label, type: "date", ...extra });
const money = (name, label) => ({ name, label, type: "number", step: "1000" });
const file = (name, label) => ({ name, label, type: "file" });

export const resources = {
  pegawai: {
    table: "pegawai",
    title: "Data Pegawai",
    icon: "bi-people-fill",
    color: "purple",
    order: "nama",
    roles: ["admin", "developer"],
    search: ["nama", "nip", "kepangkatan", "jabatan_fungsional"],
    columns: [
      ["nama", "Nama Pegawai"],
      ["nip", "NIP"],
      ["status_kepegawaian", "Status"],
      ["jabatan_fungsional", "Jabatan Fungsional"],
    ],
    fields: [
      text("nama", "Nama Lengkap", { required: true }),
      text("nip", "NIP"),
      text("tempat_lahir", "Tempat Lahir"),
      date("tanggal_lahir", "Tanggal Lahir"),
      text("kepangkatan", "Kepangkatan"),
      date("tmt_pangkat", "TMT Pangkat"),
      text("jabatan_fungsional", "Jabatan Fungsional"),
      date("tmt_jabatan", "TMT Jabatan"),
      { name: "sk_inpassing_2025", label: "SK Inpassing 2025", type: "checkbox" },
      text("ijazah", "Pendidikan / Ijazah"),
      text("status_kepegawaian", "Status Kepegawaian", { required: true }),
      date("tanggal_masuk_kerja", "Tanggal Masuk Kerja"),
      file("foto", "Foto Pegawai"),
      file("file_ijazah", "File Ijazah"),
      file("file_kepangkatan", "File Kepangkatan"),
      file("file_jabatan_fungsional", "File Jabatan Fungsional"),
    ],
  },
  surat_masuk: {
    table: "surat_masuk",
    title: "Surat Masuk",
    icon: "bi-inbox-fill",
    color: "blue",
    order: "tanggal_diterima",
    descending: true,
    roles: ["admin", "developer"],
    search: ["nomor_surat", "pengirim", "perihal"],
    columns: [
      ["nomor_surat", "Nomor Surat"],
      ["tanggal_surat", "Tanggal Surat"],
      ["tanggal_diterima", "Tanggal Diterima"],
      ["pengirim", "Pengirim"],
      ["perihal", "Perihal"],
    ],
    fields: [
      text("nomor_surat", "Nomor Surat", { required: true }),
      date("tanggal_surat", "Tanggal Surat", { required: true }),
      date("tanggal_diterima", "Tanggal Diterima", { required: true }),
      text("pengirim", "Pengirim", { required: true }),
      text("perihal", "Perihal", { required: true }),
      file("file_surat", "File Surat"),
    ],
  },
  surat_keluar: {
    table: "surat_keluar",
    title: "Surat Keluar",
    icon: "bi-send-fill",
    color: "green",
    order: "tanggal_surat",
    descending: true,
    roles: ["admin", "developer"],
    search: ["nomor_surat", "tujuan", "perihal"],
    columns: [
      ["nomor_surat", "Nomor Surat"],
      ["tanggal_surat", "Tanggal Surat"],
      ["tujuan", "Tujuan"],
      ["perihal", "Perihal"],
    ],
    fields: [
      text("nomor_surat", "Nomor Surat", { required: true }),
      date("tanggal_surat", "Tanggal Surat", { required: true }),
      text("tujuan", "Tujuan", { required: true }),
      text("perihal", "Perihal", { required: true }),
      file("file_surat", "File Surat"),
    ],
  },
  sk: {
    table: "surat_keputusan",
    title: "Surat Keputusan (SK)",
    icon: "bi-file-earmark-text-fill",
    color: "amber",
    order: "tanggal_sk",
    descending: true,
    roles: ["admin", "developer"],
    search: ["nomor_sk", "tentang"],
    columns: [
      ["nomor_sk", "Nomor SK"],
      ["tanggal_sk", "Tanggal SK"],
      ["tentang", "Tentang"],
    ],
    fields: [text("nomor_sk", "Nomor SK", { required: true }), date("tanggal_sk", "Tanggal SK", { required: true }), text("tentang", "Tentang", { required: true }), file("file_sk", "File SK")],
  },
  absensi: {
    table: "absensi",
    title: "Absensi Pegawai",
    icon: "bi-calendar2-check-fill",
    color: "blue",
    order: "tanggal",
    descending: true,
    roles: ["admin", "developer", "bendahara"],
    search: ["pegawai_id", "tanggal", "status", "keterangan"],
    columns: [
      ["pegawai_id", "ID Pegawai"],
      ["tanggal", "Tanggal"],
      ["jam_masuk", "Jam Masuk"],
      ["jam_keluar", "Jam Keluar"],
      ["status", "Status"],
      ["keterangan", "Keterangan"],
    ],
    fields: [
      text("pegawai_id", "ID Pegawai", { required: true }),
      date("tanggal", "Tanggal", { required: true }),
      { name: "jam_masuk", label: "Jam Masuk", type: "time" },
      { name: "jam_keluar", label: "Jam Keluar", type: "time" },
      { name: "status", label: "Status", type: "select", options: ["hadir", "tidak_hadir", "izin", "sakit", "cuti"] },
      text("keterangan", "Keterangan"),
    ],
  },
  pengajuan_izin: {
    table: "pengajuan_izin",
    title: "Pengajuan Izin",
    icon: "bi-clipboard-check-fill",
    color: "amber",
    order: "created_at",
    descending: true,
    roles: ["admin", "developer"],
    search: ["pegawai_id", "tanggal", "jenis", "status", "keterangan"],
    columns: [
      ["pegawai_id", "ID Pegawai"],
      ["tanggal", "Tanggal"],
      ["jenis", "Jenis"],
      ["status", "Status"],
      ["keterangan", "Keterangan"],
    ],
    fields: [
      text("pegawai_id", "ID Pegawai", { required: true }),
      date("tanggal", "Tanggal", { required: true }),
      { name: "jenis", label: "Jenis", type: "select", options: ["izin", "sakit", "dinas"] },
      text("keterangan", "Keterangan", { required: true }),
      file("file_bukti", "File Bukti"),
    ],
  },
  kas: {
    table: "kas_transaksi",
    title: "Arus Kas (Kecil & Besar)",
    icon: "bi-wallet2",
    color: "green",
    order: "tanggal",
    descending: true,
    roles: ["developer", "bendahara"],
    search: ["jenis_kas", "tipe", "kategori", "keterangan"],
    columns: [
      ["tanggal", "Tanggal"],
      ["jenis_kas", "Jenis Kas"],
      ["tipe", "Tipe"],
      ["kategori", "Kategori"],
      ["jumlah", "Jumlah"],
    ],
    fields: [
      date("tanggal", "Tanggal", { required: true }),
      { name: "jenis_kas", label: "Jenis Kas", type: "select", options: ["kas_kecil", "kas_besar"] },
      { name: "tipe", label: "Tipe", type: "select", options: ["pemasukan", "pengeluaran"] },
      text("kategori", "Kategori", { required: true }),
      text("keterangan", "Keterangan"),
      money("jumlah", "Jumlah (Rp)"),
    ],
  },
  gaji: {
    table: "gaji",
    title: "Penggajian & Slip Gaji",
    icon: "bi-cash-stack",
    color: "amber",
    order: "tahun",
    descending: true,
    roles: ["developer", "bendahara"],
    search: ["pegawai_id", "bulan", "tahun", "catatan"],
    columns: [
      ["pegawai_id", "ID Pegawai"],
      ["bulan", "Bulan"],
      ["tahun", "Tahun"],
      ["gaji_pokok", "Gaji Pokok"],
      ["total_gaji", "Total Gaji"],
    ],
    fields: [
      text("pegawai_id", "ID Pegawai", { required: true }),
      { name: "bulan", label: "Bulan", type: "number", min: 1, max: 12, required: true },
      { name: "tahun", label: "Tahun", type: "number", required: true },
      money("gaji_pokok", "Gaji Pokok"),
      money("tunj_fungsional", "Tunjangan Fungsional"),
      money("tunj_struktural", "Tunjangan Struktural"),
      money("tunj_kesejahteraan", "Tunjangan Kesejahteraan"),
      money("tunj_kawin", "Tunjangan Kawin"),
      money("tunj_anak", "Tunjangan Anak"),
      money("tunj_beras", "Tunjangan Beras"),
      money("tunjangan_makan", "Tunjangan Makan"),
      money("tunjangan_lain", "Tunjangan Lain"),
      money("pot_bpjs_tk", "Potongan BPJS TK"),
      money("pot_bpjs_kes", "Potongan BPJS Kesehatan"),
      money("pot_koperasi", "Potongan Koperasi"),
      money("potongan", "Potongan Lain"),
      money("total_gaji", "Total Gaji"),
      text("catatan", "Catatan"),
    ],
  },
};

export const formatValue = (value, field = "") => {
  if (value === null || value === undefined || value === "") return "—";
  if (field.includes("tanggal") || field === "tanggal_sk") return new Intl.DateTimeFormat("id-ID").format(new Date(`${value}T00:00:00`));
  if (
    [
      "jumlah",
      "gaji_pokok",
      "total_gaji",
      "tunj_kawin",
      "tunj_anak",
      "tunj_beras",
      "tunj_fungsional",
      "tunj_struktural",
      "tunj_kesejahteraan",
      "tunjangan_makan",
      "tunjangan_lain",
      "pot_bpjs_tk",
      "pot_bpjs_kes",
      "pot_koperasi",
      "potongan",
    ].includes(field)
  )
    return `Rp ${Number(value).toLocaleString("id-ID")}`;
  return String(value);
};
